Repository WildCodeSchool/orleans-0919-php-countryclub, pull requests merged in 2019-11, with the labels that each got.

#46 S01 us1
  composer.json
  config/db.php.dist
  public/assets/css/style.css
  public/assets/images/logo FB gris.png
  public/assets/images/logo-country-45.png
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#47 S02 us3
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Model/NewsManager.php
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Home/news.html.twig
Labels: Correction Done, Reviewed

#51 photos members
  public/assets/images/president.png
  public/assets/images/secretaire.png
  public/assets/images/tresorier.png
Labels: Reviewed

#48 S02 us6
  public/assets/css/style.css
  public/assets/font/docktrin.ttf
  public/assets/images/Laura-Huot.png
  public/assets/images/countrydanseline-min.jpg
  public/assets/images/favicon-32.png
  public/assets/images/michele-drouin.png
  public/assets/images/paysageR66.jpg
  public/assets/images/paysageR66panneau.jpg
  public/assets/images/route66paysage-min.jpg
  src/Controller/AssociationController.php
  src/Model/TeacherManager.php
  src/View/Association/index.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#52 Dev
  composer.json
  config/db.php.dist
  public/assets/css/style.css
  public/assets/font/docktrin.ttf
  public/assets/images/Laura-Huot.png
  public/assets/images/countrydanseline-min.jpg
  public/assets/images/favicon-32.png
  public/assets/images/logo FB gris.png
  public/assets/images/logo-country-45.png
  public/assets/images/michele-drouin.png
  public/assets/images/paysageR66.jpg
  public/assets/images/paysageR66panneau.jpg
  public/assets/images/president.png
  public/assets/images/route66paysage-min.jpg
  public/assets/images/secretaire.png
  public/assets/images/tresorier.png
  src/Controller/AssociationController.php
  src/Controller/HomeController.php
  src/Model/NewsManager.php
  src/Model/TeacherManager.php
  src/View/Association/index.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Home/news.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#49 S01 us4
  public/assets/css/style.css
  public/assets/images/cd2019.jpeg
  public/assets/images/cd2020.jpg
  public/assets/images/country.jpeg
  public/assets/images/facebook.png
  public/assets/images/index.png
  src/Controller/HomeController.php
  src/Model/CountryManager.php
  src/View/Home/country.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#50 S02 us6bis
  .gitignore
  public/assets/css/style.css
  public/upload/.gitkeep
  src/Controller/MemberController.php
  src/Model/MemberManager.php
  src/View/Member/index.html.twig
Labels: Correction Done

#60 S03 us61
  .gitignore
  public/assets/css/style.css
  public/assets/upload/.gitignore
  public/assets/upload/Laura-Huot.png
  public/assets/upload/michele-drouin.png
  src/View/Association/index.html.twig
Labels: Reviewed

#72 S03 us31
  public/assets/css/style.css
  public/assets/upload/Laura-Huot.png
  public/assets/upload/michele-drouin.png
  src/Controller/AdminController.php
  src/View/Admin/header.html.twig
  src/View/Admin/index.html.twig
  src/View/Association/index.html.twig
  src/View/Home/footer.html.twig
Labels: Reviewed

#75 S03 us6fix
  public/assets/css/style.css
  public/assets/images/countryDancers.jpg
  public/assets/images/danseursVectoriel.png
  public/assets/images/president.png
  public/assets/images/secretaire.png
  public/assets/images/tresorier.png
  src/Controller/AssociationController.php
  src/Model/TeacherManager.php
  src/View/Association/index.html.twig
Labels: Reviewed

#79 creation page contact
  public/assets/css/style.css
  public/assets/images/pagecontact.jpeg
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
Labels: Reviewed

#74 S02 us3
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/View/Home/country.html.twig
  src/View/Home/news.html.twig
Labels: Reviewed

#84 S03 us16
  public/assets/css/style.css
  public/assets/images/boots.jpg
  src/View/Admin/header.html.twig
  src/View/Admin/index.html.twig
Labels: Reviewed

#85 S04 us4
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/View/Admin/header.html.twig
  src/View/Home/country.html.twig
Labels: Reviewed

#87 S04 us4fix
  public/assets/css/style.css
  src/View/Home/header.html.twig
Labels: Reviewed

#86 S03 us16.1
  public/assets/css/style.css
  public/assets/images/westernAdmin.jpg
  src/Controller/AdminTeacherController.php
  src/View/Admin/Teacher/index.html.twig
Labels: Reviewed

#94 conflit de classe photo teacher
  public/assets/css/style.css
  src/View/Admin/Teacher/index.html.twig
Labels: Reviewed

#97 S03 us34
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
Labels: Reviewed

#96 S02 us3
  public/assets/css/style.css
  public/assets/images/img-news.jpg
  src/View/Home/news.html.twig
Labels: Reviewed

#98 Dev
  public/assets/css/style.css
  public/assets/images/img-news.jpg
  src/Controller/ContactController.php
  src/View/Admin/Teacher/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/news.html.twig
Labels: Reviewed

#95 S02 us22
  public/assets/css/style.css
  public/assets/images/route66bis.jpeg
  src/Controller/JoinController.php
  src/View/Home/footer.html.twig
  src/View/Join/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#100 S03 us17
  public/assets/css/style.css
  src/Controller/AdminTeacherController.php
  src/Model/TeacherManager.php
  src/View/Admin/Teacher/_form.html.twig
  src/View/Admin/Teacher/edit.html.twig
  src/View/Admin/Teacher/index.html.twig
  src/View/Admin/header.html.twig
Labels: Reviewed

#99 ajout des controlleurs et de la page galerie
  public/assets/css/style.css
  public/assets/images/pagegalerie.jpg
  src/Controller/GalleryController.php
  src/Model/GalleryManager.php
  src/View/Gallery/index.html.twig
  src/View/Home/header.html.twig
Labels: Reviewed

#102 pb conflits recup dev
  public/assets/css/style.css
  src/View/Home/footer.html.twig
Labels: Reviewed

#119 S03 us34 fix
  public/assets/css/style.css
  public/assets/images/hat2.png
  src/View/Contact/index.html.twig
Labels: Reviewed

#124 page admin member index
  public/assets/css/style.css
  src/Controller/AdminMemberController.php
  src/View/Admin/Member/index.html.twig
Labels: Reviewed

#126 Ajout de la fonctionalité update des news
  public/assets/css/style.css
  src/Controller/AdminNewsController.php
  src/Model/NewsManager.php
  src/View/Admin/News/_form.html.twig
  src/View/Admin/News/edit.html.twig
  src/View/Admin/News/index.html.twig
  src/View/Admin/header.html.twig
Labels: Reviewed

#128 update bureau
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/_form.html.twig
  src/View/Admin/Member/edit.html.twig
  src/View/Admin/header.html.twig
Labels: Reviewed

#131 Affichage des photos dans la partie admin
  src/Controller/AdminGalleryController.php
  src/View/Admin/Picture/add.html.twig
  src/View/Admin/Picture/edit.html.twig
  src/View/Admin/Picture/form.html.twig
  src/View/Admin/Picture/index.html.twig
  src/View/Admin/header.html.twig
  src/View/Gallery/index.html.twig
Labels: Reviewed

#138 S04 us18
  public/assets/css/style.css
  src/Controller/AdminTeacherController.php
  src/Model/TeacherManager.php
  src/View/Admin/Teacher/_form.html.twig
  src/View/Admin/Teacher/index.html.twig
Labels: Reviewed

#136 fix admin member
  src/View/Admin/Member/edit.html.twig
Labels: Reviewed

#139 S04 us4
  public/assets/css/style.css
  src/Controller/AdminCountryDayController.php
  src/Model/AdminCountryDayManager.php
  src/Model/CountryManager.php
  src/View/Admin/index.html.twig
  src/View/CountryDay/add.html.twig
  src/View/CountryDay/form.html.twig
  src/View/Home/country.html.twig
Labels: Correction Done, Reviewed

#140 page admin ajout member et changement BDD
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Member/edit.html.twig
  src/View/Admin/Member/index.html.twig
Labels: Reviewed

#142 fix responsive page asso
  public/assets/css/style.css
  src/View/Admin/Teacher/_form.html.twig
  src/View/Association/index.html.twig
Labels: Reviewed

#141 possibilité delete membre bureau en admin
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/index.html.twig
Labels: Reviewed

#147 modif page admin member bouton valider et retour
  src/View/Admin/Member/_form.html.twig
  src/View/Admin/Member/add.html.twig
Labels: Reviewed

#148 S04 us17.2
  config/config.php
  src/Controller/AdminTeacherController.php
  src/View/Admin/Teacher/_form.html.twig
Labels: Reviewed

#149 S04 us12
  public/assets/css/style.css
  src/View/Admin/News/add.html.twig
  src/View/Admin/News/edit.html.twig
  src/View/Admin/News/index.html.twig
Labels: Reviewed

#153 ajout mentions légales + liens
  public/assets/css/style.css
  src/Controller/MentionsLegalesController.php
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/MentionsLegales/index.html.twig
Labels: Reviewed

#155 read part of CRUD done
  public/assets/images/tresorier.png
  src/Controller/AdminCountryDayController.php
  src/Model/AdminCountryDayManager.php
  src/View/CountryDay/add.html.twig
  src/View/CountryDay/form.html.twig
  src/View/CountryDay/index.html.twig
  src/View/Home/country.html.twig
Labels: Reviewed

#156 Upload & Delete
  src/Controller/AdminGalleryController.php
  src/Model/GalleryManager.php
  src/View/Admin/Gallery/add.html.twig
  src/View/Admin/Gallery/edit.html.twig
  src/View/Admin/Gallery/form.html.twig
  src/View/Admin/Gallery/index.html.twig
  src/View/Admin/Picture/add.html.twig
  src/View/Admin/Picture/index.html.twig
  src/View/Gallery/index.html.twig
Labels: Reviewed

#154 upload admin page for members
  config/config.php
  src/Controller/AdminMemberController.php
  src/View/Admin/Member/_form.html.twig
  src/View/Admin/Member/edit.html.twig
Labels: Reviewed

#158 S04 us18.2
  public/assets/css/style.css
  src/Controller/AdminTeacherController.php
  src/View/Admin/Teacher/_form.html.twig
  src/View/Admin/Teacher/edit.html.twig
Labels: Reviewed

#159 S04 us14.2
  src/Controller/AdminMemberController.php
Labels: Reviewed

#160 fix sur la homepage
  public/assets/css/style.css
  public/assets/images/dancersVector2.png
  public/assets/images/iconeBoot.png
  public/assets/images/iconeGuitare.png
  public/assets/images/iconeHat.png
  src/View/Home/country.html.twig
  src/View/Home/index.html.twig
  src/View/Home/news.html.twig
Labels: Reviewed

#162 S04 us10.1
  src/Controller/AdminCountryDayController.php
  src/Model/AdminCountryDayManager.php
  src/View/Admin/header.html.twig
  src/View/CountryDay/edit.html.twig
  src/View/CountryDay/form.html.twig
  src/View/CountryDay/index.html.twig
Labels: Reviewed

#182 fix page contact CSS
  public/assets/css/style.css
Labels: Reviewed

#183 Ajout de la galerie modale
  public/assets/css/style.css
  src/View/Gallery/index.html.twig
Labels: Reviewed

#184 S04 fix home.2
  public/assets/css/style.css
  public/assets/images/hatWhite.png
  src/View/Home/country.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Home/news.html.twig
  src/View/Join/index.html.twig
Labels: Reviewed

#186 fix error sql suppression animatrice
  src/Controller/AdminTeacherController.php
Labels: Reviewed

#185 Fix adherer
  public/assets/css/style.css
  src/View/Home/header.html.twig
  src/View/Join/index.html.twig
Labels: Reviewed

#187 fix Admin News-CoundtyDay
  src/Controller/AdminCountryDayController.php
  src/View/Admin/News/index.html.twig
  src/View/CountryDay/index.html.twig
Labels: Reviewed

#188 fix page asso
  public/assets/css/style.css
  src/View/Association/index.html.twig
Labels: Reviewed

#189 fix retour team
  public/assets/css/style.css
  src/View/Admin/Gallery/index.html.twig
  src/View/Admin/header.html.twig
  src/View/CountryDay/add.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Join/index.html.twig
Labels: Reviewed

#190 Dev
  public/assets/css/style.css
  public/assets/images/hatWhite.png
  src/Controller/AdminCountryDayController.php
  src/Controller/AdminTeacherController.php
  src/View/Admin/Gallery/index.html.twig
  src/View/Admin/News/index.html.twig
  src/View/Admin/header.html.twig
  src/View/Association/index.html.twig
  src/View/CountryDay/add.html.twig
  src/View/CountryDay/index.html.twig
  src/View/Gallery/index.html.twig
  src/View/Home/country.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Home/news.html.twig
  src/View/Join/index.html.twig
Labels: Reviewed
